// Hand-designed levels. See level.js for the map legend.
// Angles are in degrees: 0 = east, 90 = south (screen down).
// Guard paths and demo routes use cell indices; camera and laser positions are
// exact tile coordinates (cell edges are whole numbers).

export const CHAPTERS = [
  // ====================================================================== CASE 1
  {
    id: 'gallery',
    title: 'The Gallery',
    tagline: 'Paintings, plinths and cameras that never blink.',
    blurb: 'The Aurelian Museum reopens next week. Tonight it is just you, the art and a security system that thinks it is very clever.',
    theme: 'gallery',
    levels: [
      {
        id: '1-1',
        par: 14.5,
        title: 'Opening Night',
        brief: 'Nobody’s home. Grab the painting, walk out the side door.',
        hint: 'Press on the thief, draw up to the painting, then back down to the glowing exit before you lift.',
        loot: { name: 'Portrait of a Cat in a Ruff', value: 120, kind: 'cat' },
        intro: {
          kicker: 'How it works',
          title: 'One line, one lift',
          art: 'draw',
          text: [
            'Press on the thief and draw the whole route in a single stroke: loot first, then the exit.',
            'Lift your thumb and the plan runs. There is no steering once it starts.',
          ],
          button: 'Let’s go',
        },
        demo: [[1, 11], [4, 11], [4, 5], [2, 5], [2, 3], [4, 3], [7, 3], [7, 5], [5, 5], [5, 11], [8, 11]],
        map: [
          '          ',
          '          ',
          ' ######## ',
          ' #..$...# ',
          ' #.gggg.# ',
          ' #......# ',
          ' ###..### ',
          ' #......# ',
          ' #..c...# ',
          ' #......# ',
          ' ###..### ',
          ' T......E ',
          ' ######## ',
          '          ',
          '          ',
          '          ',
        ],
      },
      {
        id: '1-2',
        par: 15.5,
        title: 'Watchful Eye',
        brief: 'One camera, staring at the middle of the room. It can’t see the walls.',
        hint: 'Hug the side walls. The coin sits just outside the light.',
        loot: { name: 'The Sapphire Sparrow', value: 180, kind: 'gem' },
        intro: {
          kicker: 'New trick',
          title: 'Stay out of the light',
          art: 'camera',
          text: [
            'Cameras see everything inside their cone of light. Walls block the view.',
            'If the thief steps into a cone, it’s over. Go around.',
          ],
        },
        map: [
          '          ',
          ' ######## ',
          ' #...$..# ',
          ' #......# ',
          ' #.####.# ',
          ' #......# ',
          ' #......# ',
          ' #......# ',
          ' #.c....# ',
          ' #......# ',
          ' #......# ',
          ' #......# ',
          ' ###..### ',
          ' #T....E# ',
          ' ######## ',
          '          ',
        ],
        cameras: [{ at: [5.0, 5.0], dir: 90, range: 4.6, fov: 46 }],
      },
      {
        id: '1-3',
        par: 12,
        title: 'Sweep',
        brief: 'This camera turns. While your thumb is down, you see where it will be when you get there.',
        hint: 'Wait below the doorway with your thumb held still. Go as soon as the light swings up.',
        loot: { name: 'Moonlight Over Marseille', value: 220, kind: 'painting' },
        intro: {
          kicker: 'New trick',
          title: 'Time follows your thumb',
          art: 'wait',
          text: [
            'While you draw, the museum shows the moment the thief reaches your fingertip.',
            'Hold your thumb still to make the thief wait. Watch the camera turn, then move on.',
          ],
        },
        tutorial: { drawing: 'The room shows the moment you reach your fingertip. Hold still to wait.' },
        demo: [[2, 11], [2, 8], [4, 7, 1.6], [4, 5], [6, 3], [7, 3]],
        map: [
          '          ',
          ' ######## ',
          ' #......# ',
          ' #.....$# ',
          ' #......# ',
          ' #..c...# ',
          ' ###.#### ',
          ' #......# ',
          ' #......# ',
          ' #......# ',
          ' #......# ',
          ' #T....E# ',
          ' ######## ',
          '          ',
          '          ',
          '          ',
        ],
        cameras: [{ at: [2.0, 2.0], dir: 45, sweep: 80, period: 6, range: 5.6, fov: 38 }],
      },
      {
        id: '1-4',
        par: 21.5,
        title: 'Crossfire',
        brief: 'Two cameras sweep the long hall. They’re almost in step. Almost.',
        hint: 'Wait in the lower room for both cameras to look away, then cross in one go.',
        loot: { name: 'The Duchess’s Egg', value: 260, kind: 'egg' },
        map: [
          '##########',
          '#...$....#',
          '#........#',
          '#..B..B..#',
          '#........#',
          '####..####',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#.......c#',
          '####..####',
          '#c.......#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        cameras: [
          { at: [1.0, 7.0], dir: 0, sweep: 90, period: 5, phase: 0, range: 7, fov: 40 },
          { at: [9.0, 9.0], dir: 180, sweep: 90, period: 5, phase: 0.35, range: 7, fov: 40 },
        ],
      },
      {
        id: '1-5',
        par: 21,
        title: 'Glass House',
        brief: 'Display cases block your way but not the camera’s view. Statues hide you.',
        hint: 'Rest in the shadow behind each statue while the camera sweeps past.',
        loot: { name: 'Blue Willow Vase', value: 310, kind: 'vase' },
        intro: {
          kicker: 'Careful',
          title: 'Glass hides nothing',
          art: 'glass',
          text: [
            'Glass cases stop you walking through, but cameras see straight through them.',
            'Solid things, like walls and statues, block the view. Use their shadows.',
          ],
        },
        map: [
          '##########',
          '#$.......#',
          '#..g..g..#',
          '#........#',
          '#.B...B..#',
          '#........#',
          '#..g..g..#',
          '#........#',
          '#.B...B..#',
          '#........#',
          '#..g..g.c#',
          '#........#',
          '###.######',
          '#........#',
          '#T......E#',
          '##########',
        ],
        cameras: [{ at: [9.0, 6.5], dir: 180, sweep: 120, period: 6, range: 9, fov: 36 }],
      },
      {
        id: '1-6',
        par: 25,
        title: 'The Curator’s Pride',
        brief: 'Two sapphires, two wings, three cameras. The curator is very proud of them.',
        hint: 'Take the left wing first. The top camera rests on each side for a moment.',
        loot: { name: 'The Twin Sapphires', value: 450, kind: 'gem' },
        map: [
          '##########',
          '#$.#..#.$#',
          '#..#..#..#',
          '#........#',
          '##.####.##',
          '#........#',
          '#.B....B.#',
          '#....c...#',
          '#........#',
          '#.B....B.#',
          '#........#',
          '####..####',
          '#........#',
          '#c.......#',
          '#T......E#',
          '##########',
        ],
        cameras: [
          { at: [5.0, 1.0], dir: 90, sweep: 150, period: 6, range: 5, fov: 40 },
          { at: [5.0, 5.0], dir: 90, sweep: 130, period: 5, phase: 0.25, range: 7, fov: 40 },
          { at: [1.0, 12.5], dir: 0, sweep: 0, range: 3.2, fov: 40 },
        ],
      },
    ],
  },

  // ====================================================================== CASE 2
  {
    id: 'bank',
    title: 'The Night Watch',
    tagline: 'A marble bank lobby and the guards who walk it all night.',
    blurb: 'Castellan & Sons keep their deposit boxes behind a lobby of marble and potted palms. The guards are bored, punctual and walk the same rounds every night.',
    theme: 'bank',
    levels: [
      {
        id: '2-1',
        par: 16,
        title: 'Rounds',
        brief: 'One guard, one hallway, the same walk all night. Cross behind his back.',
        hint: 'Wait at a doorway until he walks away from it, then cross behind him.',
        loot: { name: 'Box 214: Grandmother’s Pearls', value: 140, kind: 'necklace' },
        intro: {
          kicker: 'New trick',
          title: 'Guards walk rounds',
          art: 'guard',
          text: [
            'Guards follow the dotted route and see everything in front of them. They never look back.',
            'Don’t bump into one, even from behind.',
          ],
        },
        map: [
          '##########',
          '#...$....#',
          '#........#',
          '#.g.gg.g.#',
          '#........#',
          '###.##.###',
          '#........#',
          '#........#',
          '#.......c#',
          '###.##.###',
          '#........#',
          '#.B....B.#',
          '#........#',
          '#c.......#',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[1, 7], [8, 7]], speed: 1.3, wait: 0.8 }],
      },
      {
        id: '2-2',
        par: 21.5,
        title: 'Merry-Go-Round',
        brief: 'He walks the loop clockwise, forever. The deposit box sits at the top.',
        hint: 'Enter the loop just after he passes, and follow him at a distance.',
        loot: { name: 'Box 377: Bearer Bonds', value: 260, kind: 'briefcase' },
        map: [
          '####$#####',
          '#........#',
          '#.######.#',
          '#.#    #.#',
          '#.#    #.#',
          '#.#    #.#',
          '#.#    #.#',
          '#c#    #.#',
          '#.#    #.#',
          '#.#    #.#',
          '#.#    #.#',
          '#.######.#',
          '#........#',
          '####..####',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[1, 1], [8, 1], [8, 12], [1, 12]], loop: true, speed: 1.5, offset: 4 }],
      },
      {
        id: '2-3',
        par: 18.5,
        title: 'Crossing Paths',
        brief: 'Two guards circle two pillars. Their routes cross in the middle.',
        hint: 'Stay behind the upper guard as he rounds his pillar, then slip to the left wall.',
        loot: { name: 'Box 9: The Admiral’s Watch', value: 200, kind: 'watch' },
        map: [
          '          ',
          '##########',
          '#$.......#',
          '#........#',
          '#...BB...#',
          '#...BB...#',
          '#........#',
          '#........#',
          '#........#',
          '#...BB...#',
          '#...BB...#',
          '#........#',
          '#.......c#',
          '###..#####',
          '#T.....E.#',
          '##########',
        ],
        guards: [
          { path: [[2, 3], [7, 3], [7, 6], [2, 6]], loop: true, speed: 1.3 },
          { path: [[7, 8], [2, 8], [2, 11], [7, 11]], loop: true, speed: 1.3, offset: 3 },
        ],
      },
      {
        id: '2-4',
        par: 16,
        title: 'The Sentry',
        brief: 'This one doesn’t walk. He stands in the middle and turns, like clockwork.',
        hint: 'Watch his turns while holding still. Pass behind him while he looks the other way.',
        loot: { name: 'Box 1: The Founder’s Idol', value: 300, kind: 'idol' },
        map: [
          '          ',
          ' ######## ',
          ' #..$...# ',
          ' #......# ',
          ' ##.##### ',
          ' #.....c# ',
          ' #......# ',
          ' #......# ',
          ' #......# ',
          ' #####.## ',
          ' #......# ',
          ' #c.....# ',
          ' #T....E# ',
          ' ######## ',
          '          ',
          '          ',
        ],
        guards: [{ path: [[4, 7]], look: [0, 90, 180, 270], lookTime: 1.4, turn: 220, range: 3.6 }],
      },
      {
        id: '2-5',
        par: 27.5,
        title: 'Night Shift',
        brief: 'A guard circles the hall. A camera watches the tellers’ room. Mind both.',
        hint: 'Let the guard pass the top doorway, then hurry up the left side.',
        loot: { name: 'Box 58: Uncut Rubies', value: 280, kind: 'ruby' },
        map: [
          '##########',
          '#$..#....#',
          '#...#....#',
          '#...#..g.#',
          '#.......c#',
          '##.#######',
          '#........#',
          '#........#',
          '#..B..B..#',
          '#........#',
          '#........#',
          '######.###',
          '#........#',
          '#c.......#',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[1, 6], [8, 6], [8, 10], [1, 10]], loop: true, speed: 1.3 }],
        cameras: [{ at: [9.0, 2.5], dir: 180, sweep: 80, period: 5, range: 5.5, fov: 40 }],
      },
      {
        id: '2-6',
        par: 21.5,
        title: 'The Lobby',
        brief: 'Two guards on the lobby floor and a camera over the vault door. Busy night.',
        hint: 'The two guards meet in the middle. Cross just after they part.',
        loot: { name: 'The Castellan Crown Bond', value: 480, kind: 'scroll' },
        map: [
          '##########',
          '#...$....#',
          '#.g....g.#',
          '#........#',
          '####..####',
          '#........#',
          '#.B.gg.B.#',
          '#........#',
          '#........#',
          '#.B.gg.B.#',
          '#........#',
          '####..####',
          '#c......c#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        guards: [
          { path: [[1, 5], [8, 5]], speed: 1.4, wait: 0.6 },
          { path: [[8, 10], [1, 10]], speed: 1.4, wait: 0.6, offset: 2 },
        ],
        cameras: [{ at: [9.0, 1.5], dir: 170, sweep: 50, period: 5, range: 5, fov: 36 }],
      },
    ],
  },

  // ====================================================================== CASE 3
  {
    id: 'vault',
    title: 'Red Lines',
    tagline: 'Lasers, keycards and a vault door the size of a car.',
    blurb: 'Under the Harrow Street reserve sits a vault that has never been cracked. The lasers blink on a schedule. Schedules can be learned.',
    theme: 'vault',
    levels: [
      {
        id: '3-1',
        par: 18.5,
        title: 'Tripwire',
        brief: 'The beams blink on and off. Wait between them.',
        hint: 'Pause in the gap between each pair of beams until the next one blinks off.',
        loot: { name: 'Reserve Ingot No. 1', value: 200, kind: 'gold' },
        intro: {
          kicker: 'New trick',
          title: 'Red means no',
          art: 'laser',
          text: [
            'Touch a live laser and the alarm goes off. Faint dotted lines are beams that are off right now.',
            'Each beam keeps its own rhythm. Hold still between them and time your step.',
          ],
        },
        map: [
          '          ',
          '  ######  ',
          '  #$..c#  ',
          '  #....#  ',
          '  ##..##  ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '  ##..##  ',
          '  #T..E#  ',
          '  ######  ',
          '          ',
        ],
        lasers: [
          { a: [4, 11], b: [6, 11], on: 1.6, off: 1.4, phase: 0 },
          { a: [4, 9], b: [6, 9], on: 1.6, off: 1.4, phase: 0.9 },
          { a: [4, 7], b: [6, 7], on: 1.6, off: 1.4, phase: 1.8 },
          { a: [4, 5], b: [6, 5], on: 1.6, off: 1.4, phase: 2.6 },
        ],
      },
      {
        id: '3-2',
        par: 30.5,
        title: 'Rhythm Section',
        brief: 'Some beams never switch off. The ones that do keep a beat.',
        hint: 'Zigzag through the gaps in the solid beams and wait for the blinking one.',
        loot: { name: 'Reserve Ingots, Row C', value: 260, kind: 'gold' },
        map: [
          '##########',
          '#...$....#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#c.......#',
          '####..####',
          '#........#',
          '#T......E#',
          '##########',
        ],
        lasers: [
          { a: [1, 10], b: [6, 10] },
          { a: [4, 8], b: [9, 8] },
          { a: [1, 6], b: [6, 6] },
          { a: [4, 4], b: [9, 4] },
          { a: [6, 10], b: [9, 10], on: 1.2, off: 1.2, phase: 0 },
          { a: [1, 8], b: [4, 8], on: 1.2, off: 1.2, phase: 0.6 },
          { a: [6, 6], b: [9, 6], on: 1.2, off: 1.2, phase: 1.2 },
          { a: [1, 4], b: [4, 4], on: 1.2, off: 1.2, phase: 1.8 },
        ],
      },
      {
        id: '3-3',
        par: 29.5,
        title: 'Access Denied',
        brief: 'The vault door wants a blue keycard. The keycard is in the room below.',
        hint: 'Card first. Then wait by the blinking beam and slip past the camera to the blue door.',
        loot: { name: 'Safe Deposit Gold', value: 300, kind: 'gold' },
        intro: {
          kicker: 'New trick',
          title: 'Keycards open doors',
          art: 'key',
          text: [
            'Walk over a keycard to pick it up. Doors of the same colour slide open once you hold it.',
            'Plan it in order: the card first, then the door.',
          ],
        },
        map: [
          '##########',
          '#...#....#',
          '#.$.#..c.#',
          '#...#....#',
          '##D##....#',
          '#........#',
          '#........#',
          '#####.####',
          '#........#',
          '#.......k#',
          '#........#',
          '####.#####',
          '#........#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        cameras: [{ at: [1.0, 6.0], dir: 0, sweep: 70, period: 5, range: 5, fov: 34 }],
        lasers: [{ a: [5, 7.5], b: [6, 7.5], on: 1.4, off: 1.4, phase: 0 }],
      },
      {
        id: '3-4',
        par: 20.5,
        title: 'Security Office',
        brief: 'The night manager keeps the gold card on his desk and walks laps around it.',
        hint: 'Follow the manager’s back around the desk and snatch the card.',
        loot: { name: 'The Harrow Diamond', value: 360, kind: 'gem' },
        map: [
          '##########',
          '#..#$#...#',
          '#..#.#...#',
          '#..#Y###.#',
          '#........#',
          '#.B....B.#',
          '#........#',
          '###.##.###',
          '#........#',
          '#..gggg..#',
          '#..g.yg..#',
          '#........#',
          '####.#####',
          '#........#',
          '#T.c....E#',
          '##########',
        ],
        guards: [{ path: [[2, 8], [7, 8], [7, 11], [2, 11]], loop: true, speed: 1.3 }],
        lasers: [{ a: [1, 4.5], b: [9, 4.5], on: 1.5, off: 1.5, phase: 0.5 }],
      },
      {
        id: '3-5',
        par: 22,
        title: 'Grid Lock',
        brief: 'Blue card opens blue doors, gold opens gold. The lasers don’t care which you hold.',
        hint: 'Blue card first, then the gold card behind the blue door.',
        loot: { name: 'Plates for the Fifty', value: 420, kind: 'scroll' },
        map: [
          '##########',
          '#$.Y.....#',
          '#..#.....#',
          '####..y..#',
          '#...#....#',
          '#...##D###',
          '#........#',
          '#........#',
          '#....k...#',
          '#........#',
          '#........#',
          '####..####',
          '#c.......#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        lasers: [
          { a: [1, 7], b: [9, 7], on: 1.5, off: 1.5, phase: 0 },
          { a: [1, 10], b: [9, 10], on: 1.5, off: 1.5, phase: 0.75 },
          { a: [5, 1], b: [5, 3], on: 1.2, off: 1.4, phase: 0.4 },
          { a: [6, 5], b: [7, 5], on: 1.0, off: 1.6, phase: 1.1 },
        ],
      },
      {
        id: '3-6',
        par: 20,
        title: 'The Vault',
        brief: 'Harrow Street’s vault. Guard, camera, lasers and a door that wants its card.',
        hint: 'The guard pauses at each corner. Use those pauses.',
        loot: { name: 'The Harrow Reserve', value: 650, kind: 'gold' },
        map: [
          '##########',
          '#...$$...#',
          '#........#',
          '####DD####',
          '#........#',
          '#.B....B.#',
          '#........#',
          '#........#',
          '#.B....B.#',
          '#........#',
          '###.##.###',
          '#k.......#',
          '#........#',
          '#c.......#',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[1, 4], [8, 4], [8, 9], [1, 9]], loop: true, speed: 1.4, wait: 0.8 }],
        cameras: [{ at: [1.0, 1.5], dir: 0, sweep: 60, period: 5, range: 8, fov: 30 }],
        lasers: [
          { a: [1, 12.5], b: [9, 12.5], on: 1.6, off: 1.2, phase: 0 },
        ],
      },
    ],
  },

  // ====================================================================== CASE 4
  {
    id: 'manor',
    title: 'Creaky Manor',
    tagline: 'Old floorboards, light sleepers and a family fortune.',
    blurb: 'Lord Ashgrove’s country house has three hundred years of dust and one floorboard for every regret. Every creak brings someone to look.',
    theme: 'manor',
    levels: [
      {
        id: '4-1',
        par: 15.5,
        solverNoise: 0,
        title: 'Floorboards',
        brief: 'The butler faces the window upstairs. Step on a loose board and he’ll come to look.',
        hint: 'Thread between the loose boards. Don’t touch a single one.',
        loot: { name: 'The Ashgrove Tiara', value: 260, kind: 'tiara' },
        intro: {
          kicker: 'New trick',
          title: 'Loose boards creak',
          art: 'noise',
          text: [
            'Step on a loose floorboard and every guard nearby hears it. They walk over to look, search for a moment, then go back.',
            'That can ruin a plan. It can also move a guard exactly where you want him.',
          ],
        },
        map: [
          '          ',
          ' ######## ',
          ' #$.....# ',
          ' #......# ',
          ' ###.#### ',
          ' #......# ',
          ' #.~..~.# ',
          ' #...~..# ',
          ' #~.~..~# ',
          ' #...~..# ',
          ' #.~...c# ',
          ' ####.### ',
          ' #......# ',
          ' #T....E# ',
          ' ######## ',
          '          ',
        ],
        guards: [{ path: [[5, 2]], face: 270, hear: 7 }],
      },
      {
        id: '4-2',
        par: 24,
        solverNoise: 1,
        title: 'Distraction',
        brief: 'He guards the study door and won’t budge. Unless he hears something.',
        hint: 'Circle on the loose board in the lower room, then hurry up the left side while he goes to look.',
        loot: { name: 'The Ashgrove Will', value: 300, kind: 'scroll' },
        map: [
          '##########',
          '#...$....#',
          '#........#',
          '####.#####',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#.......c#',
          '######.###',
          '#....#...#',
          '#.~..#...#',
          '#........#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[4, 5]], face: 270, hear: 8, range: 3.6 }],
      },
      {
        id: '4-3',
        par: 13.5,
        solverNoise: 1,
        title: 'Double Act',
        brief: 'Two footmen guard two doors. The one on the left is deaf as a post.',
        hint: 'Creak the board downstairs, step aside, then take the right-hand door while he’s gone.',
        loot: { name: 'Lady Ashgrove’s Pearls', value: 320, kind: 'necklace' },
        map: [
          '##########',
          '#...$...E#',
          '#........#',
          '##.####.##',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '####..####',
          '#........#',
          '#.B....B.#',
          '#...~....#',
          '#........#',
          '#c.......#',
          '#T.......#',
          '##########',
        ],
        guards: [
          { path: [[2, 5]], face: 270, deaf: true, range: 3.6 },
          { path: [[7, 5]], face: 270, hear: 7, range: 3.6 },
        ],
      },
      {
        id: '4-4',
        par: 16,
        solverNoise: 1,
        title: 'The Study',
        brief: 'The librarian watches the laser fence like a hawk. He does have excellent hearing.',
        hint: 'Creak the board in the lower room, tuck in behind a bookcase, then cross the beams while he’s gone.',
        loot: { name: 'First Folio', value: 380, kind: 'scroll' },
        map: [
          '##########',
          '#...$...E#',
          '#.g....g.#',
          '#........#',
          '##......##',
          '#........#',
          '#........#',
          '#........#',
          '###....###',
          '#........#',
          '#.B....B.#',
          '#.......~#',
          '#........#',
          '#c.......#',
          '#T.......#',
          '##########',
        ],
        guards: [{ path: [[1, 6]], face: 0, range: 7.5, fov: 50, hear: 9 }],
        lasers: [
          { a: [2, 4.5], b: [8, 4.5], on: 1.4, off: 1.2, phase: 0 },
          { a: [3, 8.5], b: [7, 8.5], on: 1.4, off: 1.2, phase: 0.7 },
        ],
      },
      {
        id: '4-5',
        solverNoise: 2,
        title: 'Cat and Mouse',
        brief: 'One guard at the jewel room door. Draw him out to get in. Draw him in to get out.',
        hint: 'Creak the board by the right door and run up the left side. Inside, creak the second board, wait by the loot and slip out behind him.',
        loot: { name: 'The Ashgrove Emerald Idol', value: 420, kind: 'idol' },
        map: [
          '##########',
          '#$.......#',
          '#gggg..~.#',
          '#........#',
          '####.#####',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#.######.#',
          '#........#',
          '#.......~#',
          '#........#',
          '#c.......#',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[4, 7]], face: 270, hear: 7, range: 3.6 }],
      },
      {
        id: '4-6',
        solverNoise: 1,
        title: 'The Master Suite',
        brief: 'His Lordship’s bedroom. A footman at the door, a camera on the landing, loose boards everywhere.',
        hint: 'Creak the board downstairs, take the right-hand stairs, time the landing camera, and leave by the bedroom window.',
        loot: { name: 'The Ashgrove Crown', value: 600, kind: 'crown' },
        map: [
          '##########',
          '#$......E#',
          '#........#',
          '#.g....g.#',
          '#####.####',
          '#.c......#',
          '#..~..~..#',
          '#........#',
          '##.####.##',
          '#..#  #..#',
          '#..####..#',
          '#~.......#',
          '#.......c#',
          '###..#####',
          '#T.......#',
          '##########',
        ],
        guards: [
          { path: [[5, 6]], face: 270, hear: 7, range: 3.6 },
        ],
        cameras: [
          { at: [1.0, 6.0], dir: 0, sweep: 50, period: 4, range: 5, fov: 32 },
        ],
      },
    ],
  },

  // ====================================================================== CASE 5
  {
    id: 'tower',
    title: 'Lights Out',
    tagline: 'Forty floors up, and a fuse box that controls everything.',
    blurb: 'The Meridian Tower keeps the Crown Jewels on tour in its penthouse. The whole floor runs on one old fuse box. Somebody should really fix that.',
    theme: 'tower',
    levels: [
      {
        id: '5-1',
        par: 10.5,
        title: 'Blackout',
        brief: 'Three cameras cover the hall. Flip the fuse and they’re blind for five seconds.',
        hint: 'Hit the fuse box and sprint straight through the hall. Leave by the window.',
        loot: { name: 'The Meridian Opal', value: 400, kind: 'gem' },
        powerDuration: 5,
        intro: {
          kicker: 'New trick',
          title: 'Kill the lights',
          art: 'power',
          text: [
            'Step on a fuse box and every camera and laser goes dark for a few seconds.',
            'Guards keep their torches. The ring around the box shows how long you have.',
          ],
        },
        map: [
          '##########',
          '#.......E#',
          '#..$.....#',
          '#........#',
          '####..####',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '####..####',
          '#........#',
          '#........#',
          '#P.c.....#',
          '#T.......#',
          '##########',
        ],
        cameras: [
          { at: [1.0, 5.5], dir: 20, range: 7, fov: 40 },
          { at: [9.0, 7.5], dir: 180, range: 7, fov: 40 },
          { at: [1.0, 9.5], dir: -20, range: 7, fov: 40 },
        ],
      },
      {
        id: '5-2',
        par: 14,
        title: 'Short Circuit',
        brief: 'The beams around the vault never blink. The fuse box is past the guard.',
        hint: 'Reach the fuse box behind the guard, then run for the beams before they return.',
        loot: { name: 'Sceptre of the Meridian', value: 460, kind: 'crown' },
        powerDuration: 6,
        map: [
          '##########',
          '#...$....#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#........#',
          '#P.......#',
          '#........#',
          '#......c.#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[1, 8], [8, 8]], speed: 1.4, wait: 0.5 }],
        lasers: [
          { a: [1, 4], b: [9, 4] },
          { a: [1, 6], b: [9, 6] },
        ],
      },
      {
        id: '5-3',
        par: 22.5,
        title: 'Penthouse Party',
        brief: 'Guests gone, staff tidying up. The cameras sleep when the power does. The staff don’t.',
        hint: 'Blackout first, then slip behind the steward while he walks the far side of the room.',
        loot: { name: 'Diamond Choker', value: 480, kind: 'necklace' },
        powerDuration: 6,
        map: [
          '##########',
          '#$.......#',
          '#..g..g..#',
          '#........#',
          '#.g..g...#',
          '#........#',
          '###.##.###',
          '#........#',
          '#..B..B..#',
          '#........#',
          '#P.......#',
          '###..#####',
          '#c.......#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        guards: [{ path: [[1, 3], [8, 3], [8, 5], [1, 5]], loop: true, speed: 1.2 }],
        cameras: [
          { at: [9.0, 7.5], dir: 180, sweep: 60, period: 4, range: 7, fov: 40 },
          { at: [1.0, 1.0], dir: 45, sweep: 50, period: 5, range: 5, fov: 36 },
        ],
      },
      {
        id: '5-4',
        par: 23.5,
        title: 'Skybridge',
        brief: 'A glass bridge between towers. Nowhere to hide, and the beams keep a brisk beat.',
        hint: 'Cross in the gaps: short dash, wait, short dash.',
        loot: { name: 'The Twin-Tower Sapphire', value: 520, kind: 'gem' },
        powerDuration: 4,
        map: [
          '##########',
          '#.$....c.#',
          '#........#',
          '####..####',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '   #..#   ',
          '####..####',
          '#P.......#',
          '#........#',
          '#T......E#',
          '##########',
        ],
        lasers: [
          { a: [4, 10], b: [6, 10], on: 1.2, off: 1.0, phase: 0 },
          { a: [4, 8.5], b: [6, 8.5], on: 1.2, off: 1.0, phase: 0.55 },
          { a: [4, 7], b: [6, 7], on: 1.2, off: 1.0, phase: 1.1 },
          { a: [4, 5.5], b: [6, 5.5], on: 1.2, off: 1.0, phase: 1.65 },
        ],
        cameras: [{ at: [4.0, 3.3], dir: 80, sweep: 36, period: 3, range: 4.2, fov: 30 }],
        guards: [{ path: [[1, 2], [8, 2]], speed: 1.2, wait: 1 }],
      },
      {
        id: '5-5',
        solverNoise: 1,
        title: 'The Long Dark',
        brief: 'The beam across the vault never blinks. Five seconds of dark is all you get. Leave by the roof.',
        hint: 'Creak the loose tile to pull the guard right, then hit the fuse and sprint up the left for the roof.',
        loot: { name: 'The Meridian Orb', value: 560, kind: 'egg' },
        powerDuration: 5,
        map: [
          '##########',
          '#$......E#',
          '#........#',
          '#........#',
          '#####.####',
          '#........#',
          '#........#',
          '#.......~#',
          '#........#',
          '#####.####',
          '#........#',
          '#.B...B..#',
          '#P......c#',
          '#........#',
          '#T.......#',
          '##########',
        ],
        guards: [{ path: [[2, 6], [7, 6]], speed: 1.2, wait: 1, hear: 6 }],
        lasers: [{ a: [1, 2.5], b: [9, 2.5] }],
        cameras: [{ at: [4.9, 10.0], dir: 90, sweep: 90, period: 4, range: 5, fov: 36 }],
      },
      {
        id: '5-6',
        par: 19.5,
        solverNoise: 0,
        title: 'The Crown Jewels',
        brief: 'The Sovereign Crown, on loan for one night only. Everything they have is guarding it.',
        hint: 'Keycard on the right, fuse box on the left. The blackout gives you five seconds to reach and cross the beam.',
        loot: { name: 'The Sovereign Crown', value: 1500, kind: 'crown' },
        powerDuration: 5,
        intro: {
          kicker: 'Final job',
          title: 'The Crown Jewels',
          art: 'crown',
          text: [
            'Everything you’ve learned, in one room. Take your time. The plan only has to work once.',
          ],
          button: 'Let’s do this',
        },
        map: [
          '##########',
          '#...$...E#',
          '#.g....g.#',
          '#........#',
          '####DD####',
          '#........#',
          '#.B....B.#',
          '#........#',
          '#P.....~.#',
          '###.##.###',
          '#........#',
          '#...~...k#',
          '#c......c#',
          '###..#####',
          '#T.......#',
          '##########',
        ],
        guards: [
          { path: [[3, 5], [6, 5], [6, 7], [3, 7]], loop: true, speed: 1.2, wait: 0.4 },
          { path: [[2, 10], [7, 10]], speed: 1.1, wait: 0.8, offset: 2 },
        ],
        cameras: [
          { at: [9.0, 6.0], dir: 180, sweep: 60, period: 5, range: 6, fov: 34 },
          { at: [1.0, 1.5], dir: 20, sweep: 50, period: 4, range: 4.5, fov: 36 },
        ],
        lasers: [{ a: [1, 3], b: [9, 3] }],
      },
    ],
  },
];
